version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_ekklesia
    environment:
      MYSQL_DATABASE: ekklesia_db
      MYSQL_USER: ekklesia_user
      MYSQL_PASSWORD: ekklesia_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ekklesia-net

  app:
    build: .
    container_name: ekklesia_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ekklesia_db
      SPRING_DATASOURCE_USERNAME: ekklesia_user
      SPRING_DATASOURCE_PASSWORD: ekklesia_pass
    depends_on:
      - db
    networks:
      - ekklesia-net

volumes:
  db_data:

networks:
  ekklesia-net:
